const { precacheAndRoute, cleanupOutdatedCaches } = require('workbox-precaching');
const { registerRoute } = require('workbox-routing');
const { StaleWhileRevalidate } = require('workbox-strategies');
const { CacheableResponsePlugin } = require('workbox-cacheable-response');
const { ExpirationPlugin } = require('workbox-expiration');

// Precache all the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST || []);

// Cleanup outdated caches
cleanupOutdatedCaches();

// Cache the CSS, JS, and HTML files using a StaleWhileRevalidate strategy.
registerRoute(
  ({ request }) => request.destination === 'style' ||
                   request.destination === 'script' ||
                   request.destination === 'document',
  new StaleWhileRevalidate({
    cacheName: 'asset-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Ensure the service worker takes control of the page as soon as it's activated.
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});
